sudo: required
services:
  - docker

before_install:
  - docker build -t lgjohnson/docker-react -f Dockerfile.dev .

script:
  - docker run lgjohnson/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "Amazon S3/elasticbeanstalk-us-west-2-119459060071"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
